project:
  type: website
  render:
    - "*.qmd"
    - "!posts/**/notebooks/"
    - "!posts/**/notebook/"

website:
  title: "Iyed Ghedamsi"
  description: "Building Data Solutions for Social Good"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iyedg/
      - icon: linkedin
        href: https://www.linkedin.com/in/iyed-ghedamsi/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



